version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
environment:
  NUGET_API_KEY:
    secure: /FLJCPNtLDyXDbw62wnY4tBc3kRJMPNbttutkzVhCdUDEmg9pjEBGZnBVpBTemKK
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
build_script:
- cmd: .\build.cmd test
- sh: ./build.sh test
test: off
